// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using EStore.Models;
#nullable enable

namespace EStore.Data;

public class AppDbContext : DbContext
{
    public DbSet<Product> Products {get; set;}
    public DbSet<Order> Orders {get; set;}
    public AppDbContext(DbContextOptions<AppDbContext> options)
    {
    }

    public AppDbContext()
    {
        
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseNpgsql("Server=127.0.0.1;Port=5432;Database=EStore;User Id=SpringBootAdmin;Password=spring;Pooling=true;MinPoolSize=1;MaxPoolSize=1000;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

    }  



}
